export const USER_ACCESS_PERMISSIONS = [
  { code: "SalesOrders.View", group: "Sales", label: "View sales orders" },
  { code: "SalesOrders.Create", group: "Sales", label: "Create sales orders" },
  { code: "SalesOrders.EditDraft", group: "Sales", label: "Edit draft orders" },
  { code: "SalesOrders.Confirm", group: "Sales", label: "Confirm orders" },
  { code: "SalesOrders.Cancel", group: "Sales", label: "Cancel orders" },
  { code: "SalesOrders.Close", group: "Sales", label: "Close orders" },
  { code: "SalesOrders.VoidPrepared", group: "Sales", label: "Void prepared orders" },
  { code: "SalesOrders.ApplyDiscount", group: "Sales", label: "Apply discounts" },
  { code: "Payments.View", group: "Payments", label: "View payments" },
  { code: "Payments.Receive", group: "Payments", label: "Receive payment" },
  { code: "Payments.Refund", group: "Payments", label: "Refund payment" },
  { code: "Payments.Configure", group: "Payments", label: "Configure payment methods" },
  { code: "Pos.View", group: "POS", label: "View POS" },
  { code: "Pos.Configure", group: "POS", label: "Configure terminals" },
  { code: "Pos.OpenShift", group: "POS", label: "Open shift" },
  { code: "Pos.CloseShift", group: "POS", label: "Close shift" },
  { code: "Pos.AdjustCashDrawer", group: "POS", label: "Adjust cash drawer" },
  { code: "Pos.PrintReceipt", group: "POS", label: "Print receipt" },
  { code: "Kitchen.View", group: "Kitchen", label: "View kitchen" },
  { code: "Kitchen.Manage", group: "Kitchen", label: "Manage kitchen" },
  { code: "Inventory.View", group: "Inventory", label: "View inventory" },
  { code: "Inventory.Configure", group: "Inventory", label: "Configure inventory" },
  { code: "Inventory.AdjustStock", group: "Inventory", label: "Adjust stock" },
  { code: "Catalog.View", group: "Catalog", label: "View catalog" },
  { code: "Catalog.Manage", group: "Catalog", label: "Manage catalog" },
  { code: "Pricing.View", group: "Pricing", label: "View pricing" },
  { code: "Pricing.Manage", group: "Pricing", label: "Manage pricing" },
  { code: "Tax.View", group: "Tax", label: "View tax" },
  { code: "Tax.Manage", group: "Tax", label: "Manage tax" },
  { code: "Restaurant.View", group: "Restaurant", label: "View restaurant" },
  { code: "Restaurant.Manage", group: "Restaurant", label: "Manage restaurant" },
  { code: "Branches.View", group: "Company", label: "View branches" },
  { code: "Branches.Manage", group: "Company", label: "Manage branches" },
  { code: "Company.View", group: "Company", label: "View company" },
  { code: "Company.Manage", group: "Company", label: "Manage company" },
  { code: "Users.View", group: "Users & Access", label: "View users" },
  { code: "Users.Manage", group: "Users & Access", label: "Manage users" },
  { code: "Roles.View", group: "Users & Access", label: "View roles" },
  { code: "Roles.Manage", group: "Users & Access", label: "Manage roles" },
  { code: "Purchases.View", group: "Purchases", label: "View purchases" },
  { code: "Purchases.Manage", group: "Purchases", label: "Manage purchases" },
  { code: "Purchases.Receive", group: "Purchases", label: "Receive purchases" },
  { code: "Customers.View", group: "Customers", label: "View customers" },
  { code: "Customers.Manage", group: "Customers", label: "Manage customers" },
  { code: "Devices.View", group: "Devices", label: "View devices" },
  { code: "Devices.Manage", group: "Devices", label: "Manage devices" },
  { code: "EdgeAgents.View", group: "Devices", label: "View edge agents" },
  { code: "EdgeAgents.Manage", group: "Devices", label: "Manage edge agents" },
] as const;

const ENTITLEMENT_BY_PREFIX: Record<string, string> = {
  "Inventory.": "INVENTORY",
  "Pos.": "POS",
  "Restaurant.": "RESTAURANT",
  "Kitchen.": "RESTAURANT.KITCHEN",
  "Purchases.": "PROCUREMENT",
};

export function getPermissionEntitlement(code: string) {
  const match = Object.entries(ENTITLEMENT_BY_PREFIX).find(([prefix]) => code.startsWith(prefix));
  return match?.[1] ?? null;
}
