// Application route constants
export const ROUTES = {
  LOGIN: "/",
  SIGNUP: "/signup",
  DASHBOARD: "/dashboard",
  POS: "/POSPage",
  POS_SHIFT_HISTORY: "/pos/shifts",
  POS_TERMINALS_ADMIN: "/pos/terminals/admin",
  RESTAURANT_ADMIN: "/restaurant/admin",
  KITCHEN: "/kitchen",
  KITCHEN_ADMIN: "/kitchen/admin",
  SALES: "/sales",
  PURCHASES: "/purchases",
  INVENTORY: "/inventory",
  CUSTOMERS: "/customers",
  SUPPLIERS: "/suppliers",
  ACCOUNTING: "/accounting",
  REPORTS: "/reports",
  PROJECTS: "/projects",
  HR: "/hr",
  SETTINGS: "/settings",
  MORE: "/more",
  PROFILE: "/profile",
  NOT_FOUND: "*",
};
