// Application route constants
export const ROUTES = {
  LOGIN: "/",
  SIGNUP: "/signup",
  DASHBOARD: "/dashboard",
  POS: "/POSPage",
  KITCHEN: "/kitchen",
  SALES: "/sales",
  PURCHASES: "/purchases",
  INVENTORY: "/inventory",
  CUSTOMERS: "/customers",
  SUPPLIERS: "/suppliers",
  ACCOUNTING: "/accounting",
  REPORTS: "/reports",
  PROJECTS: "/projects",
  HR: "/hr",
  SETTINGS: "/settings",
  MORE: "/more",
  PROFILE: "/profile",
  NOT_FOUND: "*",
};
